version: '3'
services:
  backend:
    build:
      context: ./backend  # En donde se encuentra el archivo Dockerfile
    
    image: sebastianwebapp/ejercicio_2:latest  # Nombre y etiqueta de la imagen en Docker Hub

    ports:
      - "4000:4000"  # Mapea el puerto 4000 del contenedor al 4000 de tu máquina
    volumes:
      - ./backend:/app  # Monta el código fuente en el contenedor para facilitar el desarrollo

    networks:
      - my_network  # Conectar el backend a la red personalizada

  frontend:
    build:
      context: ./frontend
    
    image: sebastianwebapp/ejercicio_2:latest  # Nombre y etiqueta de la imagen en Docker Hub

    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al 3000 de tu máquina
    volumes:
      - ./frontend:/app
    depends_on:
      - backend  # Asegura que el backend se ejecute primero
    networks:
      - my_network  # Conectar el frontend a la misma red personalizada

networks:
  my_network:
    driver: bridge  # Definir la red como una red de puente (bridge)

