version: '3.8'

services:
  backend:
    image: sebastianwebapp/ejercicio_2_backend:latest
    build:
      context: ./backend  # Ruta del directorio del backend
    container_name: my_backend
    ports:
      - "4000:4000"

  frontend:
    image: sebastianwebapp/ejercicio_2_frontend:latest
    build:
      context: ./frontend  # Ruta del directorio del frontend
    container_name: my_frontend
    ports:
      - "3000:3000"

