version: '3.8'

services:
  backend:
    image: sebastianwebapp/ejercicio_2_backend:latest
    build:
      context: ./backend  # Ruta del directorio del backend
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - app_network  # Red compartida

  frontend:
    image: sebastianwebapp/ejercicio_2_frontend:latest
    build:
      context: ./frontend  # Ruta del directorio del frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app_network  # Red compartida

networks:
  app_network:
    driver: bridge  # Red puente para comunicación entre servicios
