name: CI/CD Pipeline for Ejercicio_2

on:
  push:
    branches:
      - main  # Puedes cambiar la rama según sea necesario

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verificar la instalación de Docker Compose

      # Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Asegúrate de que los secretos estén configurados
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker images using Docker Compose
      - name: Build and tag Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      # Push the Docker images to Docker Hub
      - name: Push Docker images to DockerHub
        run: |
          docker-compose -f docker-compose.yml push


  deploy-to-ec2:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
        - name: Trigger redeploy on EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST_DNS }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              docker pull sebastianwebapp/ejercicio_2_backend:latest
              docker pull sebastianwebapp/ejercicio_2_frontend:latest
              docker stop my_backend || true
              docker stop my_frontend || true
              docker rm my_backend || true
              docker rm my_frontend || true
              docker run -d --name my_backend sebastianwebapp/ejercicio_2_backend:latest
              docker run -d --name my_frontend sebastianwebapp/ejercicio_2_frontend:latest
              echo "Desplegando en ${{ secrets.HOST_DNS }} con la rama ${{ github.ref_name }}"
              sleep 10
              docker ps | grep my_backend || echo "El contenedor backend no está corriendo correctamente"
              docker ps | grep my_frontend || echo "El contenedor frontend no está corriendo correctamente"

  
