name: CI/CD Pipeline for Ejercicio_2

on:
  push:
    branches:
      - main  # Cambia según sea necesario

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Docker and Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker --version  # Verificar la instalación de Docker
          docker-compose --version  # Verificar la instalación de Docker Compose

      # Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Asegúrate de que los secretos estén configurados
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images using Docker Compose
      - name: Build and tag Docker images with Docker Compose
        run: |
          # Construir las imágenes con Docker Compose
          docker-compose -f docker-compose.yml build

          # Subir las imágenes a Docker Hub
          docker-compose -f docker-compose.yml push

